### ISSUE TITLE
[bug] JUnitTest failed

### ISSUE THREAD

**Issue by DingXuefeng** [HorizonAsk/hoawiki-backend#33]
Currently all JUnitTest failed on my local test environment.

Two exceptions are thrown. One of them is throw in this method:

```java
sun.security.util;

public class PolicyUtil {

...
    public static KeyStore getKeyStore
                (URL policyUrl,                 // URL of policy file
                String keyStoreName,            // input: keyStore URL
                String keyStoreType,            // input: keyStore type
                String keyStoreProvider,        // input: keyStore provider
                String storePassURL,            // input: keyStore password
                Debug debug)
        throws KeyStoreException, MalformedURLException, IOException,
                NoSuchProviderException, NoSuchAlgorithmException,
                java.security.cert.CertificateException {

        if (keyStoreName == null) {
            throw new IllegalArgumentException("null KeyStore name");
        }
```

**Comment by saltball** [comment]
We have CI#34. And unittests really fail if one did't set the env variables. So no bug(

**Comment by DingXuefeng** [comment]
The exceptions, however, are still thrown, and thus JUnitTest still failed under debug mode. Can you run them under the debug mode? @saltball 

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/3205938/159968750-9becad55-ec2c-4f9f-8c8f-bcc533de5f2c.png">

**Comment by DingXuefeng** [comment]
The exceptions is due to the missing `keystore` configuration in the policy. In the default policies, this is not set.

`keystore` is useful when [setting the SSL and Https](https://docs.oracle.com/javase/tutorial/security/userperm/policy.html). See also [explanation of keystore](https://docs.oracle.com/javase/7/docs/technotes/guides/security/PolicyFiles.html#:~:text=com.mycom.MyPolicy-,Policy%20File%20Syntax,-The%20policy%20configuration).

In principle this should be all automatical. Not sure why it's missing here.
