### ISSUE TITLE
[note] Continuous integration of JUnitTest

### ISSUE THREAD

**Issue by DingXuefeng** [HorizonAsk/hoawiki-backend#34]
**Is your feature request related to a problem? Please describe.**
Run unit test in continuous integration.

**Describe the solution you'd like**
Run unit-test in github-actions

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by saltball** [comment]
CI test is being with action `Java CI with Gradle` and also docker action in build progress.

Maybe you didn't setting up the **environment variables** running tests as the action did:

See ReadMe:
https://github.com/HorizonAsk/hoawiki-backend/blob/6c40ac0bbf690ca7d445f6bacd6e77cee12b1800/README.md?plain=1#L48-L62

Or refer to the action file:
https://github.com/HorizonAsk/hoawiki-backend/blob/6c40ac0bbf690ca7d445f6bacd6e77cee12b1800/.github/workflows/gradle.yml#L42

And I have test, without these settings, the CI failed also. (e.g. https://github.com/HorizonAsk/hoawiki-backend/runs/4913076808)

**Comment by DingXuefeng** [comment]
I think my confusion arises from the special grammar of gradle.

I assume
```shell
gradle build
```
only compile java source code into byte-code, while actually this command will run all tasks specified in the gradle.build. 

```
> Task :compileJava
> Task :processResources
> Task :classes
> Task :bootJar
> Task :jar
> Task :assemble
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
> Task :check
> Task :build
```

This is not so intuitive. 

Since CI is included in `.github/workflows/gradle.yml` properly, this issue can be closed.
